version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
    command: ./bin/webpack-dev-server --public
    volumes:
      - .:/myapp
    ports:
      - '3035:3035'
